### ISSUE TITLE
Join Entries "Street" and "House number" to street address

### ISSUE THREAD

**Issue by dlang9159** [KircheNeuenburg/ldapcontacts#13]
In most applications these 2 fields are joined in a "street address" field.
It would be more convenient to also use this format. For example otrs doesn't display the housing number, since it expects this to be in the street address field.

See [this format guide](http://www.bitboost.com/ref/international-address-formats/germany/) as a reference

**Comment by dlang9159** [comment]
Also [this schema](http://schema.org/PostalAddress)

**Comment by alexhor** [comment]
In v1.1 it will be possible for the admin to define which LDAP attributes to use.
