### ISSUE TITLE
LDAP attribute: postalAddress

### ISSUE THREAD

**Issue by linuxrrze** [KircheNeuenburg/ldapcontacts#17]
Hi there,

I just tried the ldapcontacts app for the first time, and (once I figured out
which attributes to provide) I found that the content of the postalAddress
LDAP attribute is displayed as "House number".

However according to RFC this should contain a whole adress
with multiple lines separated by "$":

https://www.ietf.org/rfc/rfc2252.txt?number=2252

Hope this helps to improve this app.

BTW: I hat to scan through the source code in order to find
         the attribute list to provide. It'd make things much easier
         if first time users could read about that in the docs (or
         getting a list in the config dialog ...)

Just in case someone else is looking for them:

`lib/Controller/ContactController.php:`

> givenname,sn,street,postaladdress,postalcode,l,homephone,mobile,description

**Comment by alexhor** [comment]
Thanks for the input!
In the next version it will be possible for you to define the LDAP attributes as you see fit yourself.
