### ISSUE TITLE
ldapcontacts problem

### ISSUE THREAD

**Issue by caroberto6** [KircheNeuenburg/ldapcontacts#24]
Hi,

the application doesn't work for us with the newest version of app and Nextcloud (I had the same problem with previous versions, too).

When I click on the app icon, I got the following error message:

This page isn’t working
nextcloud.giganet.hu is currently unable to handle this request.
HTTP ERROR 500

And I can't see any option on the setting page just circling hourglass icons:
![image](https://user-images.githubusercontent.com/20857803/36585749-717c5950-187f-11e8-8096-3cc12e055d23.png)

Any guess what the problem is?

Best regards,
Robert

**Comment by alexhor** [comment]
What does your nextcloud log say?
What is your setup (web-/ ldapserver / OS)?

**Comment by caroberto6** [comment]
log messages:

- when I enable the plugin: Error | PHP | Undefined index: @value at /var/www/html/nextcloud/lib/private/legacy/app.php#1170
- when I try to open the contacts page or the settings page: Error | PHP | syntax error, unexpected '>' at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#336

setup:
webserver: apache 2.4.10
ldapserver: samba4
OS: Debian 8

**Comment by alexhor** [comment]
That looks like your are not using php 7?
Sorry, I should put that in the requirements.
I am using some new operators, introduced in php 7.

**Comment by caroberto6** [comment]
Yes, you got it, we use 5.6.33.
Thanks for the help we are going to update it.

Have a nice day!

**Comment by caroberto6** [comment]
Hi,

now the settings page works, but I can't get the users. Now the contacts page has the circling hourglass icons.

I deleted all the unnecessary LDAP user attributes and changed the LDAP attributes as I found in our LDAP config.
![image](https://user-images.githubusercontent.com/20857803/36664899-53f6d4d2-1ae6-11e8-843e-665f0abc7327.png)

We can login into Nextlcou with LDAP, so the system works but I miss some LDAPcontacts settings I guess. Any idea how to continue?

**Nextcloud log:**
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
-- | -- | -- | --
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#751 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#674 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#674 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#696 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#674 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#696 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#674 | 2018-02-26T11:10:34+0100
Error | PHP | ldap_search(): Search: Operations error at /var/www/html/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#254 | 2018-02-26T11:10:34+0100



logs:

**Comment by alexhor** [comment]
I'll have a look at this at the end of the coming week

**Comment by caroberto6** [comment]
Cool, thank you!

**Comment by caroberto6** [comment]
Hi Alex,

do you have some idea how to continue with the setting?

thanks in advance,
Robert

**Comment by alexhor** [comment]
The app uses Nextclouds internal ldap search now, so this should be resolved.
