### ISSUE TITLE
Group Mapping doesn't work

### ISSUE THREAD

**Issue by Koma-Andrea** [KircheNeuenburg/ldapcontacts#25]
no matter what values I enter in the Attribute values, the group are either not filtered (every user is in every group) or i none.
No Group:
![no group](https://user-images.githubusercontent.com/247170/36874269-8d491764-1dab-11e8-87a1-d4cebf2ed396.PNG)

All tthe groups:
![all groups](https://user-images.githubusercontent.com/247170/36874280-95dd7992-1dab-11e8-8306-04f41fe4e33e.PNG)

NextCloud is actually managing well the user/group mappings looks like the problem is only in the app.
Also using the companion app "LDAP Organisation" it shows all the groups containing no user or either no group at all.

Some info:
I'm using FreeIPA
I've more then 100 groups
I've more than 500 users
I'm using without any issue the memberof mapping for other application.
I've set advanced filters for users/group/logins in the main ldap section.

**Comment by alexhor** [comment]
you store the group membership in the memberof attribute of each user?

**Comment by koma85** [comment]
I store the users in the member attribute of the group and the group  in the attribute memberof of the user

**Comment by koma85** [comment]
To help you:
This is an user  (admin) in LDAP (FreeIPA Default confgiuration and schema)
![user_smudge](https://user-images.githubusercontent.com/247170/36966686-dbef1b2a-205d-11e8-838e-b3e3d9f66b8c.png)
Which as you can see is memberof the group admins
And this is a Group (the group admins of course, where you can see the user Admin is member).
![group_smudge](https://user-images.githubusercontent.com/247170/36966692-e329d51a-205d-11e8-9594-be5f05737c9f.png)

**Comment by koma85** [comment]
Also memberOf is capable of managing multi level and linked groups.
Admins is member of group A and group A is member of Group B
So if you search in group B you will find admin as member. (Mind tricky but simple to search).

**Comment by alexhor** [comment]
under "LDAP Group attribute used for group membership" you should put "member" and under "LDAP User attribute used for group membership" you should put the attribute for "uid=admin,cn=users,cn=accounts,dc=..." (I am guessing dn?!)
Let me know if this works for you.
I put together a small explemation for all the settings, hopefully that helps as well:
https://github.com/KircheNeuenburg/ldapcontacts/wiki/Settings-Documentation

The memberOf attribute is currently not supported by this app.

**Comment by vahem2lu** [comment]
I think it's related to: https://github.com/KircheNeuenburg/ldapcontacts/issues/33#issuecomment-420195891

I saw from var dump that "LDAP User attribute used for group membership" gets somehow to HEX format and breaks LDAP filter.

If I remove ldap_escape filter is correct, I get results, but return $groups still crashes whole App.

**Comment by alexhor** [comment]
The app uses nextclouds own ldap mappers so this should be resolved.
