### ISSUE TITLE
[Suggestion] Preview of search filter

### ISSUE THREAD

**Issue by koma85** [KircheNeuenburg/ldapcontacts#28]
Would be very useful to have a preview of the LDAP search that is going to be executed

**Comment by alexhor** [comment]
you mean a string preview of the query?

**Comment by koma85** [comment]
Yes that's what I mean. Sorry for my English. Is not my first language.

**Comment by alexhor** [comment]
Is this looking good?

<img width="493" alt="search filter preview" src="https://user-images.githubusercontent.com/6049831/37585849-c03f42c6-2b5a-11e8-9673-7313d21e0af8.PNG">

**Comment by koma85** [comment]
I'll try tomorrow
