### ISSUE TITLE
LDAP groups not showing in ldapcontacts and ldaporg

### ISSUE THREAD

**Issue by winnall** [KircheNeuenburg/ldapcontacts#29]
I’m using Nextcloud 13.0.0 on Ubuntu 16.04 with OpenLDAP (slapd) 2.4.42. Under `/settings/user` and `/settings/users` I can see my LDAP groups, so they do seem to be set up properly.

But under `/apps/ldaporg` and `/apps/ldapcontacts` they do not show up.

**Comment by winnall** [comment]
I've just updated to Nextcloud 13.0.1 and the behaviour has changed.

Some groups do now appear under `/apps/ldaporg` and `/apps/ldapcontacts`: however, it is always the same four, regardless of the group membership of the users concerned.

`/settings/user` and `/settings/users` are still correct.

**Comment by alexhor** [comment]
Cloud you post your ldapcontacts settings here.
Maybe check the new settings documentation as well:
https://github.com/KircheNeuenburg/ldapcontacts/wiki/Settings-Documentation

Are there any errors in your Nextcloud logs?

**Comment by winnall** [comment]
Thanks for taking some time for this.

There are no errors in my Nextcloud error log, except for `access forbidden by rule, ... "GET /data/.ocdata?t=NNNNN HTTP/2.0"`.

My access log contains the following for a call to `/apps/ldapcontacts`:

>NN.NNN.NNN.NN - - [19/Mar/2018:15:50:17 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:18 +0000] "GET /apps/ldapcontacts HTTP/2.0" 200 6472 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /css/core/1cf341db-jquery-ui-fixes.css?v=7e4c2a73-4 HTTP/2.0" **499** 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /css/core/1cf341db-server.css?v=7e4c2a73-4 HTTP/2.0" **499** 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /css/core/1cf341db-share.css?v=7e4c2a73-4 HTTP/2.0" **499** 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /css/core/1cf341db-jquery.ocdialog.css?v=7e4c2a73-4 HTTP/2.0" **499** 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:19 +0000] "GET /apps/ldapcontacts/load HTTP/2.0" 200 2082 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:20 +0000] "GET /apps/ldapcontacts/own HTTP/2.0" 200 1319 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:20 +0000] "GET /apps/ldapcontacts/groups HTTP/2.0" 200 1247 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:20 +0000] "GET /apps/ldapcontacts/settings HTTP/2.0" 200 903 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:21 +0000] "GET /apps/ldapcontacts/settings/personal/tutorial_state HTTP/2.0" 200 679 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - - [19/Mar/2018:15:50:21 +0000] "POST /apps/ldapcontacts/settings/personal HTTP/2.0" 200 718 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
NN.NNN.NNN.NN - admin [19/Mar/2018:15:50:26 +0000] "PROPFIND /remote.php/dav/files/admin/ HTTP/1.1" **207** 505 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)"

They're all 200s, except the ones in bold.

The settings for ldapcontacts are as follows:


Attribute |  Value
-- | --
Login Attribut |  mail
LDAP Benutzerattribut das für die Gruppenmitgliedschaft benutzt wird |  memberof
LDAP Gruppenattribut das für die Gruppenmitgliedschaft benutzt wird |  member
Login Bearbeiten URL ändern |  
Einzigartige LDAP Eintrag Identifizierung |  entryuuid

and

LDAP Attribut | Bezeichnung
-- | --
givenname  | First Name
sn | Last Name 

with NO hidden users and NO hidden groups.

`./occ ldap:show-config` gives me the following:

Configuration | Value
-- | --
hasMemberOfFilterSupport | 
hasPagedResultSupport | 
homeFolderNamingRule | 
lastJpegPhotoLookup | 0                                               
ldapAgentName | cn=admin,dc=XXXXXXXX,dc=YYYYYY                  
ldapAgentPassword | ***                                             
ldapAttributesForGroupSearch | 
ldapAttributesForUserSearch | 
ldapBackupHost | 
ldapBackupPort | 
ldapBase | dc=XXXXXXXX, dc=YYYYYY                          
ldapBaseGroups | ou=groups, dc=XXXXXXXX, dc=YYYYYY               
ldapBaseUsers | ou=people, dc=XXXXXXXX, dc=YYYYYY               
ldapCacheTTL | 600                                             
ldapConfigurationActive | 1                                               
ldapDefaultPPolicyDN | 
ldapDynamicGroupMemberURL | 
ldapEmailAttribute | mail                                            
ldapExperiencedAdmin | 1                                               
ldapExpertUUIDGroupAttr | 
ldapExpertUUIDUserAttr | 
ldapExpertUsernameAttr | 
ldapGidNumber | gidNumber                                       
ldapGroupDisplayName | cn                                              
ldapGroupFilter | (\&(\|(objectclass=groupOfNames)))                
ldapGroupFilterGroups | 
ldapGroupFilterMode | 0                                               
ldapGroupFilterObjectclass | groupOfNames                                    
ldapGroupMemberAssocAttr | member                                          
ldapHost | ldap://localhost                                
ldapIgnoreNamingRules | 
ldapLoginFilter | (\&(\|(objectclass=inetOrgPerson))(\|(mail=%uid))) 
ldapLoginFilterAttributes | 
ldapLoginFilterEmail | 0                                               
ldapLoginFilterMode | 0                                               
ldapLoginFilterUsername | 0                                               
ldapNestedGroups | 1                                               
ldapOverrideMainServer | 
ldapPagingSize | 500                                             
ldapPort | 389                                             
ldapQuotaAttribute | 
ldapQuotaDefault | 
ldapTLS | 0                                               
ldapUserDisplayName | cn                                              
ldapUserDisplayName2 | 
ldapUserFilter | (\|(objectclass=inetOrgPerson))                  
ldapUserFilterGroups | 
ldapUserFilterMode | 0                                               
ldapUserFilterObjectclass | inetOrgPerson                                   
ldapUuidGroupAttribute | auto                                            
ldapUuidUserAttribute | auto                                            
turnOffCertCheck | 0                                               
turnOnPasswordChange | 0                                              
useMemberOfToDetectMembership | 0

**Comment by winnall** [comment]
The subset of four groups that I mentioned above is also listed on `https://cloud.winnall.net/settings/admin/ldap` in the LDAP Org settings:

Superuser Gruppe:   Executive Board   IT and Internet    Projects   Steering Committees

**Comment by alexhor** [comment]
The contacts are beeing displayed corretl, just the groups are missing right?

**Comment by winnall** [comment]
I should probably mention that I am using recursive groups (i.e. LDAP groupOfNames containing - directly or indirectly - other groupOfNames). I should have mentioned this at the outset - sorry.

**Comment by alexhor** [comment]
is it possible that only the top level groups are shown and the other 12 groups are children?

**Comment by winnall** [comment]
Is this issue now resolved?

**Comment by alexhor** [comment]
The app uses nextclouds integrated group search now, so all groups should show up.
