### ISSUE TITLE
Undefined index entryuuid

### ISSUE THREAD

**Issue by vahem2lu** [KircheNeuenburg/ldapcontacts#33]
Hi

Using Nextcloud 13.0.1 with latest ldapcontacts and PHP 7.2.

`Undefined index: entryuuid at ...../apps\/ldapcontacts\/lib\/Controller\/ContactController.php#390`

Is PHP7.2 unsupported and only PHP7.0 is supported?

LDAP login and connections are working okay (I have two LDAP endpoints configured).

**Comment by alexhor** [comment]
I am guessing, that you are using active directory?
The attribute "entryuuid" isn't supported there.
You can replace it in the settings with "dn", but the disadvantage is that "dn" can change and "entyuuid" woun't.

**Comment by vahem2lu** [comment]
Thanks for quick reply.
I am using SAMBA and AD (two LDAP connections). Neither of them are working. I even cannot configure ldapcontacts plugin from Settings.

**Comment by alexhor** [comment]
What do you mean you can't configure the plugin from settings?
Is it not loading?

**Comment by vahem2lu** [comment]
See attachment 
![screen shot 2018-04-12 at 13 10 02](https://user-images.githubusercontent.com/15649157/38670966-e2631ed0-3e52-11e8-8c61-77ce9f674d35.png)

**Comment by vahem2lu** [comment]
Any news?

**Comment by vahem2lu** [comment]
After changing:

Using only one LDAP connection to AD

Changes in files: **lib/Controller/SettingsController.php**
Lines 52 and 53
`uid` => `sAMAccountName`
Line 59
`entryuuid` => `dn`

I get only statistics view, but log still shows error (with no content)

```
/---/
"method":"GET","url":"\/apps\/ldapcontacts\/groups","message":"Exception: ","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
```

**Comment by vahem2lu** [comment]
Changed SettingsController.php file.
`entry_id_attribute` from `entryuuid` to `dn`
and user_group_id_group_attribute` value to `member` (instead of `memberUid`)
and faking **function getGroups** to return null (in file `ContactController.php`
I get admin view (with settings) and person view with contacts. But there's some case with groups, because it breaks the whole plugin.

**Comment by vahem2lu** [comment]
"LDAP User attribute used for group membership" gets somehow to HEX format and breaks LDAP filter.

See settings
![screen shot 2018-09-11 at 11 41 33](https://user-images.githubusercontent.com/15649157/45348643-e0cd6580-b5b7-11e8-8e9a-e7293de6b61a.png)

And error
![screen shot 2018-09-11 at 11 41 41](https://user-images.githubusercontent.com/15649157/45348642-e0cd6580-b5b7-11e8-93cc-eec58e0422f5.png)

**Comment by alexhor** [comment]
Entryuuid is now fetched from nextcloud itself, so this shouldn't be an issue anymore.
