### ISSUE TITLE
Adding LDAP User Attributes from admin screen does nothing

### ISSUE THREAD

**Issue by vahem2lu** [KircheNeuenburg/ldapcontacts#36]
When I add new attribute from "LDAP User Attributes" screen in admin, page saves, but after a reload everything stays the same, so I cannot add new attributes to display.

**Comment by vahem2lu** [comment]
Okay, found a way.
* Add new attribute by clicking "+ Add Attribute"
* Fill in necessary fields
* Jump to already existing field and change content there
* Click anywhere out from the box
* jQuery automatic save occurs
* all fields are saved.

**Comment by alexhor** [comment]
Saving via save button now
