### ISSUE TITLE
ldap_search(): Search: Can't contact LDAP server

### ISSUE THREAD

**Issue by zicklag** [KircheNeuenburg/ldapcontacts#38]
Hi, I am trying to get set up with LDAP contacts but I am getting the following error:

```
count():  Parameter must be an array or an object that implements Countable at  /var/www/html/custom_apps/ldapcontacts/lib/Controller/ContactController.php#737
ldap_search():  Search: Can't contact LDAP server at  /var/www/html/custom_apps/ldapcontacts/lib/Controller/ContactController.php#255
```

Before installing LDAP Contacts I successfully configured the " LDAP user and group backend" plugin that comes with Nextcloud. I can log in with my LDAP credentials and everything works fine until I install the LDAP Contacts plugin. If I try to hit the LDAP Contacts app page, it takes a very long time before getting to the page and it endlessly shows the loading icons.

As far as I understand the LDAP Contacts plugin should be using the connections settings from builtin Nextcloud LDAP app so it shoudn't have any issues. Does anybody have any idea what's going on?

I am using Nextcloud 13.0.6 using the official Docker container.

**Comment by alexhor** [comment]
The app now uses nextclouds native LDAP integration.
