### ISSUE TITLE
Incompatibility to Nextcloud 19

### ISSUE THREAD

**Issue by wolfff** [KircheNeuenburg/ldapcontacts#44]
When installing the LdapContacts plug-on on Nextcloud 19, accessing the LDAPContacts showed spinning wheels forever and the server log showed error 500 on:
GET /apps/ldapcontacts/groups
GET /apps/ldapcontacts/own
GET /apps/ldapcontacts/load

Nextcloud logging reveals:
Argument 3 passed to OCA\User_LDAP\Access::search() must be of the type array or null, string given, called in /var/www/html/apps/user_ldap/lib/Access.php on line 1009
and
Argument 2 passed to OCA\User_LDAP\Access::search() must be of the type string, array given, called in /var/www/html/custom_apps/ldapcontacts/lib/LDAP/LdapUser.php on line 62

**Comment by wolfff** [comment]
for a possible solution see https://github.com/KircheNeuenburg/ldapcontacts/pull/43

**Comment by alexhor** [comment]
Update is now available in the appstore
