### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by Nicalicious** [KircheNeuenburg/LdapContacts#54]
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://h-software.de/nextcloud_apps/ldapcontacts/ldapcontacts-2.0.5.tar.gz

**Comment by Nicalicious** [comment]
It looks like the cert for https://h-software.de/nextcloud_apps/ldapcontacts/ldapcontacts-2.0.5.tar.gz is a Let's Encrypt cert that expired on  Tuesday, July 12, 2022 at 10:34:20 PM. 
![image](https://user-images.githubusercontent.com/38387334/202302972-8fcd7bd7-07c1-49a5-a5d5-8cd315f3db11.png)

**Comment by alexhor** [comment]
Thanks for pointing this out.
Automatic certificate renewal was broken and now working again.
